spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

wuxin:
  wechat-pay:
    enabled: false
  mock-payment:
    enabled: true
