export const ROUTES = {
  home: '/pages/home/index',
  login: '/pages/login/index',
  cart: '/pages/cart/index',
  addressList: '/pages/address/list/index',
  addressEdit: '/pages/address/edit/index',
  merchantApply: '/pages/apply/merchant/index',
  riderApply: '/pages/apply/rider/index',
  orderList: '/pages/order/list/index',
  profile: '/pages/profile/index',
  profileEdit: '/pages/profile/edit/index',
  search: '/pages/search/index',
  storeList: '/pages/store/list/index',
  storeDetail: '/pages/store/detail/index',
  productDetail: '/pages/product/detail/index',
  checkout: '/pages/checkout/index',
  orderDetail: '/pages/order/detail/index',
  paymentProcessing: '/pages/payment/processing/index',
  paymentSuccess: '/pages/payment/success/index',
  paymentFailure: '/pages/payment/failure/index',
  publicService: '/pages/public/index',
  about: '/pages/about/index',
  settings: '/pages/settings/index'
} as const;
