import { updateBusinessStatus, updateStore } from '../../api/merchant';
import { BUSINESS_STATUS } from '../../constants/status';
import { refreshMerchantProfile } from '../../services/auth';
import { errorMessage } from '../../utils/request';

Page({
  data: { storeName: '', storeLogo: '', storeDescription: '', storePhone: '', province: '', city: '', district: '', detailAddress: '', latitude: '', longitude: '', openTime: '08:00', closeTime: '22:00', businessStatus: 0, businessText: '', saving: false, switching: false },
  onShow() { void this.load(); },
  async load() { try { const p = await refreshMerchantProfile(); this.setData({ storeName: p.storeName, storeLogo: p.storeLogo || '', storeDescription: p.storeDescription || '', storePhone: p.storePhone, province: p.province || '', city: p.city || '', district: p.district || '', detailAddress: p.detailAddress, latitude: p.latitude == null ? '' : String(p.latitude), longitude: p.longitude == null ? '' : String(p.longitude), openTime: (p.openTime || '08:00').slice(0,5), closeTime: (p.closeTime || '22:00').slice(0,5), businessStatus: p.businessStatus, businessText: p.businessStatusText }); } catch (error) { wx.showToast({ title: errorMessage(error), icon: 'none' }); } },
  onInput(event: WechatMiniprogram.Input) { this.setData({ [String(event.currentTarget.dataset.field)]: event.detail.value.trim() }); }, onOpenTime(event: WechatMiniprogram.PickerChange) { this.setData({ openTime: String(event.detail.value) }); }, onCloseTime(event: WechatMiniprogram.PickerChange) { this.setData({ closeTime: String(event.detail.value) }); },
  async onSave() { if (!this.data.storeName || !this.data.storePhone || !this.data.detailAddress || this.data.saving) { wx.showToast({ title: '请填写店铺名称、电话和地址', icon: 'none' }); return; } this.setData({ saving: true }); try { await updateStore({ storeName: this.data.storeName, storeLogo: this.data.storeLogo || undefined, storeDescription: this.data.storeDescription || undefined, storePhone: this.data.storePhone, province: this.data.province || undefined, city: this.data.city || undefined, district: this.data.district || undefined, detailAddress: this.data.detailAddress, latitude: this.data.latitude ? Number(this.data.latitude) : undefined, longitude: this.data.longitude ? Number(this.data.longitude) : undefined, openTime: `${this.data.openTime}:00`, closeTime: `${this.data.closeTime}:00` }); await refreshMerchantProfile(); wx.showToast({ title: '店铺资料已更新', icon: 'success' }); } catch (error) { wx.showToast({ title: errorMessage(error), icon: 'none' }); } finally { this.setData({ saving: false }); } },
  async onSwitchBusiness() { if (this.data.switching) return; const next = this.data.businessStatus === BUSINESS_STATUS.open ? BUSINESS_STATUS.closed : BUSINESS_STATUS.open; const result = await wx.showModal({ title: next === BUSINESS_STATUS.open ? '开始营业' : '暂停营业', content: next === BUSINESS_STATUS.open ? '营业后用户可浏览商品并加入购物车。' : '休息后公开商品将暂不可见，确定继续？', confirmColor: next === BUSINESS_STATUS.open ? '#18a660' : '#e5484d' }); if (!result.confirm) return; this.setData({ switching: true }); try { await updateBusinessStatus(next); await this.load(); wx.showToast({ title: next === 1 ? '店铺已营业' : '店铺已休息', icon: 'success' }); } catch (error) { wx.showToast({ title: errorMessage(error), icon: 'none' }); } finally { this.setData({ switching: false }); } }
});
