import { createProduct, getCategories, updateProduct } from '../../api/catalog';
import type { Category, Product } from '../../types/product';
import { errorMessage } from '../../utils/request';
const DRAFT_KEY = 'WUXIN_MERCHANT_PRODUCT_EDIT';

Page({
  data: { id: 0, categories: [] as Category[], categoryIndex: 0, productName: '', productImage: '', productDescription: '', price: '', originalPrice: '', stock: '0', sort: '0', saving: false },
  async onLoad(options: Record<string, string>) { const id = Number(options.id || 0); const draft = wx.getStorageSync<Product>(DRAFT_KEY); this.setData({ id: Number.isInteger(id) && id > 0 ? id : 0 }); try { const categories = await getCategories(); const enabled = categories.filter(item => item.status === 1 || item.categoryId === draft?.categoryId); const categoryIndex = Math.max(0, enabled.findIndex(item => item.categoryId === draft?.categoryId)); this.setData({ categories: enabled, categoryIndex }); if (id && draft?.productId === id) this.setData({ productName: draft.productName, productImage: draft.productImage || '', productDescription: draft.productDescription || '', price: String(draft.price), originalPrice: draft.originalPrice == null ? '' : String(draft.originalPrice), stock: String(draft.stock), sort: String(draft.sort || 0) }); } catch (error) { wx.showToast({ title: errorMessage(error), icon: 'none' }); } },
  onInput(event: WechatMiniprogram.Input | WechatMiniprogram.TextareaInput) { this.setData({ [String(event.currentTarget.dataset.field)]: event.detail.value.trim() }); }, onCategory(event: WechatMiniprogram.PickerChange) { this.setData({ categoryIndex: Number(event.detail.value) }); },
  async save() { if (this.data.saving) return; const category = this.data.categories[this.data.categoryIndex]; if (!category || !this.data.productName.trim() || !/^\d+(\.\d{1,2})?$/.test(this.data.price) || Number(this.data.price) <= 0 || !/^\d+$/.test(this.data.stock)) { wx.showToast({ title: '请检查分类、名称、价格和库存', icon: 'none' }); return; } if (this.data.originalPrice && (!/^\d+(\.\d{1,2})?$/.test(this.data.originalPrice) || Number(this.data.originalPrice) <= 0)) { wx.showToast({ title: '商品原价格式不正确', icon: 'none' }); return; } this.setData({ saving: true }); try { const payload = { categoryId: category.categoryId, productName: this.data.productName.trim(), productImage: this.data.productImage.trim() || undefined, productDescription: this.data.productDescription.trim() || undefined, price: Number(this.data.price), originalPrice: this.data.originalPrice ? Number(this.data.originalPrice) : undefined, stock: Number(this.data.stock), sort: Number(this.data.sort) || 0 }; if (this.data.id) await updateProduct(this.data.id, payload); else await createProduct(payload); wx.removeStorageSync(DRAFT_KEY); wx.showToast({ title: '商品已保存', icon: 'success' }); setTimeout(() => wx.navigateBack(), 600); } catch (error) { wx.showToast({ title: errorMessage(error), icon: 'none' }); } finally { this.setData({ saving: false }); } }
});
